import type { DriverJobDto } from '@api/models/job.models';
import { VEHICLE_IMAGE_URLS } from './vehicleImages';

/** Network-shaped job list — same contract as live `/Driver/Api/fetchJobList`. */
export const JOBS_SEED: DriverJobDto[] = [
  {
    job_id: 'JOB-9001',
    job_type: 'delivery',
    priority: 'same_day',
    job_status: 'assigned',
    booking_id: 44821,
    booking_reference: 'LGC-2026-44821',
    customer_name: 'Sara K.',
    customer_phone_masked: '+971 50 *** **12',
    vehicle: {
      make: 'Nissan',
      model: 'Altima',
      year: 2023,
      plate_number: 'D 98765',
      color: 'White',
      image_url: VEHICLE_IMAGE_URLS.sedanWhite,
    },
    branch_name: 'Legend Dubai Marina',
    scheduled_at: '2026-05-26T14:00:00+04:00',
    pick_up_address: 'Legend Dubai Marina Branch',
    drop_off_address: 'Marina Walk, Dubai Marina, Dubai',
    latitude: 25.0805,
    longitude: 55.1403,
    delivery_status: 'paid_delivery',
    notes: 'Customer requested call 10 min before arrival.',
  },
  {
    job_id: 'JOB-9002',
    job_type: 'return_collection',
    priority: 'overdue_return',
    job_status: 'assigned',
    booking_id: 44102,
    booking_reference: 'LGC-2026-44102',
    customer_name: 'Omar H.',
    customer_phone_masked: '+971 55 *** **88',
    vehicle: {
      make: 'Hyundai',
      model: 'Tucson',
      year: 2022,
      plate_number: 'C 44102',
      color: 'Black',
      image_url: VEHICLE_IMAGE_URLS.crossover,
    },
    branch_name: 'Legend Al Quoz',
    scheduled_at: '2026-05-26T16:30:00+04:00',
    drop_off_address: 'JLT Cluster Y, Dubai',
    latitude: 25.0697,
    longitude: 55.1425,
    collection_form_summary:
      'Preferred window: 16:00–18:00. Parking P2 slot 44. Vehicle may have low fuel.',
  },
  {
    job_id: 'JOB-9003',
    job_type: 'chauffeur',
    priority: 'urgent',
    job_status: 'accepted',
    booking_id: 45001,
    booking_reference: 'LGC-2026-45001',
    customer_name: 'Fatima A.',
    customer_phone_masked: '+971 52 *** **01',
    vehicle: {
      make: 'Mercedes-Benz',
      model: 'E-Class',
      year: 2024,
      plate_number: 'L 10001',
      color: 'Silver',
      image_url: VEHICLE_IMAGE_URLS.luxury,
    },
    branch_name: 'Legend Downtown',
    scheduled_at: '2026-05-26T18:00:00+04:00',
    pick_up_address: 'DIFC Gate Avenue',
    drop_off_address: 'Dubai Mall, Fountain Views',
    latitude: 25.1972,
    longitude: 55.2744,
    notes: 'Book with Driver — 4 hours, 2 stops. No self-drive.',
  },
  {
    job_id: 'JOB-9004',
    job_type: 'pickup',
    priority: 'normal',
    job_status: 'assigned',
    booking_id: 44700,
    booking_reference: 'LGC-2026-44700',
    customer_name: 'James R.',
    customer_phone_masked: '+971 54 *** **77',
    vehicle: {
      make: 'Toyota',
      model: 'Corolla',
      year: 2024,
      plate_number: 'E 22001',
      color: 'Grey',
      image_url: VEHICLE_IMAGE_URLS.compact,
    },
    branch_name: 'Legend Business Bay',
    scheduled_at: '2026-05-27T09:00:00+04:00',
    pick_up_address: 'Business Bay, Bay Square',
    drop_off_address: 'Legend Business Bay Branch',
    latitude: 25.1852,
    longitude: 55.2734,
    delivery_status: 'self_pickup',
  },
  {
    job_id: 'JOB-9005',
    job_type: 'delivery',
    priority: 'urgent',
    job_status: 'en_route',
    booking_id: 44990,
    booking_reference: 'LGC-2026-44990',
    customer_name: 'Layla M.',
    customer_phone_masked: '+971 56 *** **33',
    vehicle: {
      make: 'Kia',
      model: 'Sportage',
      year: 2023,
      plate_number: 'F 33009',
      color: 'Blue',
      image_url: VEHICLE_IMAGE_URLS.suv,
    },
    branch_name: 'Legend Al Quoz',
    scheduled_at: '2026-05-26T11:30:00+04:00',
    pick_up_address: 'Legend Al Quoz Branch',
    drop_off_address: 'Mirdif City Centre area',
    latitude: 25.2215,
    longitude: 55.4103,
    delivery_status: 'paid_delivery',
  },
];
