import { Dimensions, Platform, StyleSheet } from 'react-native';
import { BrandColors, Colors } from '@constants/colors';
import { APP_FONTS } from '@constants/appFonts';
import { TextStyles } from '@constants/textStyles';
import { addAlpha, type ThemeTokens } from '@theme/index';

export const createAuthStyles = (theme: ThemeTokens) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: theme.background,
    },
    bg: {
      flex: 1,
      justifyContent: 'flex-end',
    },
    bgImage: {
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      height: '62%',
      width: '100%',
    },
    overlay: {
      ...StyleSheet.absoluteFill,
      backgroundColor: 'rgba(0,0,0,0.28)',
    },
    sheet: {
      borderTopLeftRadius: 32,
      borderTopRightRadius: 32,
      backgroundColor: theme.surface,
      paddingHorizontal: 24,
      paddingTop: 28,
      paddingBottom: 36,
      shadowColor: theme.name === 'dark' ? '#000' : BrandColors.brandDeep,
      shadowOpacity: 0.18,
      shadowRadius: 24,
      shadowOffset: { width: 0, height: -8 },
      elevation: 12,
      marginTop: -24,
    },
    welcomeSection: {
      alignItems: 'center',
      marginBottom: 8,
    },
    welcomeIconContainer: {
      width: 76,
      height: 76,
      borderRadius: 38,
      backgroundColor: addAlpha(BrandColors.accentOrange, 0.12),
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 18,
      borderWidth: 2,
      borderColor: addAlpha(BrandColors.accentOrange, 0.22),
    },
    brandBadge: {
      fontFamily: APP_FONTS.bold,
      fontSize: 11,
      letterSpacing: 3,
      color: BrandColors.accentOrange,
      marginBottom: 6,
    },
    title: {
      ...TextStyles.h2,
      textAlign: 'center',
      color: theme.text,
      marginBottom: 8,
    },
    subtitle: {
      textAlign: 'center',
      color: theme.textSecondary,
      fontSize: 14,
      lineHeight: 20,
      marginBottom: 4,
      fontFamily: APP_FONTS.regular,
    },
    phoneRow: {
      marginTop: 16,
      height: 56,
      borderRadius: 16,
      backgroundColor: theme.name === 'dark' ? theme.elevatedSurface : '#FAFAFB',
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 14,
      borderWidth: 2,
      borderColor: addAlpha(BrandColors.accentOrange, 0.22),
      shadowColor: '#000',
      shadowOpacity: 0.06,
      shadowRadius: 8,
      shadowOffset: { width: 0, height: 2 },
      elevation: 2,
    },
    ccWrap: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingRight: 10,
    },
    countryPickerBtn: {
      alignItems: 'center',
      justifyContent: 'center',
    },
    callingCode: {
      fontFamily: APP_FONTS.bold,
      fontSize: 16,
      color: theme.text,
      marginLeft: 4,
    },
    divider: {
      width: 1.5,
      height: 32,
      backgroundColor: addAlpha(BrandColors.accentOrange, 0.28),
      marginHorizontal: 10,
    },
    phoneInput: {
      flex: 1,
      fontSize: 16,
      fontFamily: APP_FONTS.regular,
      color: theme.text,
      paddingVertical: Platform.OS === 'ios' ? 8 : 6,
    },
    primaryBtn: {
      marginTop: 24,
      height: 56,
      borderRadius: 16,
      backgroundColor: BrandColors.accentOrange,
      alignItems: 'center',
      justifyContent: 'center',
      flexDirection: 'row',
      shadowColor: BrandColors.accentOrange,
      shadowOpacity: 0.35,
      shadowRadius: 12,
      shadowOffset: { width: 0, height: 6 },
      elevation: 6,
    },
    primaryBtnDisabled: {
      opacity: 0.55,
    },
    primaryTxt: {
      color: Colors.white,
      fontFamily: APP_FONTS.bold,
      fontSize: 16,
      letterSpacing: 0.3,
    },
    errorText: {
      color: Colors.danger,
      fontSize: 13,
      marginTop: 12,
      textAlign: 'center',
      fontFamily: APP_FONTS.regular,
    },
    modalBackdrop: {
      flex: 1,
      backgroundColor: theme.overlay,
      justifyContent: 'flex-end',
    },
    bottomSheet: {
      backgroundColor: theme.surface,
      borderTopLeftRadius: 32,
      borderTopRightRadius: 32,
      paddingHorizontal: 24,
      paddingTop: 16,
      paddingBottom: 32,
      maxHeight: '90%',
      minHeight: Math.min(Dimensions.get('window').height * 0.58, 520),
    },
    grabber: {
      alignSelf: 'center',
      width: 56,
      height: 5,
      borderRadius: 3,
      backgroundColor: addAlpha(BrandColors.accentOrange, 0.35),
      marginBottom: 20,
    },
    otpHeader: {
      alignItems: 'center',
      marginBottom: 28,
    },
    otpIconContainer: {
      width: 88,
      height: 88,
      borderRadius: 44,
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 18,
      backgroundColor: addAlpha(BrandColors.accentOrange, 0.12),
      borderWidth: 2,
      borderColor: addAlpha(BrandColors.accentOrange, 0.25),
    },
    otpTitle: {
      fontFamily: APP_FONTS.bold,
      fontSize: 26,
      color: theme.text,
      marginBottom: 10,
    },
    otpDesc: {
      textAlign: 'center',
      color: theme.textSecondary,
      fontSize: 15,
      lineHeight: 22,
      paddingHorizontal: 12,
      fontFamily: APP_FONTS.regular,
    },
    otpRow: {
      marginVertical: 8,
    },
    resendRow: {
      flexDirection: 'row',
      justifyContent: 'center',
      alignItems: 'center',
      marginTop: 20,
      marginBottom: 8,
      flexWrap: 'wrap',
    },
    resendMuted: {
      color: theme.textSecondary,
      fontSize: 14,
      fontFamily: APP_FONTS.regular,
    },
    resendLink: {
      color: BrandColors.accentOrange,
      fontFamily: APP_FONTS.bold,
      fontSize: 14,
    },
    verifyBtn: {
      marginTop: 16,
      height: 56,
      borderRadius: 16,
      backgroundColor: BrandColors.accentOrange,
      alignItems: 'center',
      justifyContent: 'center',
    },
    verifyBtnDisabled: {
      opacity: 0.55,
    },
    verifyTxt: {
      color: Colors.white,
      fontFamily: APP_FONTS.bold,
      fontSize: 16,
    },
    changeNumber: {
      marginTop: 16,
      alignSelf: 'center',
    },
    changeNumberTxt: {
      color: BrandColors.accentOrange,
      fontFamily: APP_FONTS.bold,
      fontSize: 14,
    },
    rtlText: {
      textAlign: 'right',
      writingDirection: 'rtl',
    },
    ltrText: {
      textAlign: 'left',
      writingDirection: 'ltr',
    },
  });

export type AuthStyles = ReturnType<typeof createAuthStyles>;
